version: 2.1

orbs:
  aws-rotate-keys: ovotech/aws-rotate-keys

jobs:
  rotate-aws-keys:
    executor: rotate-aws-keys/default
    steps:
      - rotate-aws-keys/rotate:
          aws-username: circleci-user
          circleci-token: $CIRCLECI_TOKEN1

workflows:
  version: 2
  rotate-weekly:
    triggers:
      - schedule:
          cron: "30 10 * * 3" 
          filters: { branches: { only: aws-rotate } }
    jobs:
      - rotate-aws-keys