version: 2.1

orbs:
  aws-rotate-keys: ovotech/aws-rotate-keys@1.0.220

jobs:
  rotate-aws-keys:
    executor: rotate-aws-keys/default
    steps:
      - rotate-aws-keys/rotate:
          aws-username: tfdevrole
          circleci-token: $CIRCLECI_TOKEN1

workflows:
  version: 2
  rotate-weekly:
    triggers:
      - schedule:
          cron: "* * * * *" 
          filters: { branches: { only: aws-rotate } }
    jobs:
      - rotate-aws-keys